<?php

namespace WorkshopBundle\Repository;

use WorkshopBundle\Entity\User;

/**
 * ScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTotalScoreByUser(User $user)
    {
        $qb = $this->createQueryBuilder('s');

        $qb
            ->select('SUM(s.points as totalPoints')
            ->where($qb->expr()->eq('s.user', ':user'))
            ->setParameter('user', $user);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
