<?php

namespace WorkshopBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $qb = $this->createQueryBuilder('u');

        $qb
            ->orderBy('u.totalScore', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
